// src/routes/error/+page.svelte
<script>
	import { page } from '$app/stores';
	import {onMount} from "svelte";

	$: errorMessage = '';
	onMount(() => {
		errorMessage = $page.url.searchParams.get('message') || 'No error from the backend :(';
	})
</script>

<div class="container container-center">
	<h1>Something went wrong:</h1>
	<p>{errorMessage}</p>
</div>

// src-qwik/routes/error/index.tsx
import { component$ } from '@builder.io/qwik';
import { useLocation } from '@builder.io/qwik-city';

export default component$(() => {
    const loc = useLocation();

    return (
        <>
            <div class="container container-center container-spacing-xl">
                <h3>Something went wrong</h3>
            </div>
            <div class="container">
                <p>{loc.url.searchParams.get("message")}</p>
            </div>
        </>
    );
});
